# Generated by Django 5.0.1 on 2024-09-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("key", models.CharField(max_length=13)),
            ],
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=122),
        ),
    ]
